# Configurações do servidor
server.port=8080

# Nome da aplicação
spring.application.name=agencia-viagens-api

# Configurações de JSON (opcional, mas recomendado)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
